require('./shapefile.css');
var proj4 = require('proj4/dist/proj4');
window.proj4 = proj4;
import JSZip from 'lib/jszip';
window.JSZip = JSZip;
import JSZipUtils from 'lib/jszip-utils';
window.JSZipUtils = JSZipUtils;
import 'lib/preprocess';
import loadshp from 'lib/preview.js';
window.loadshp = loadshp;
import './subir.js';
require('./popup.css');
import './popup.js';
